language: ruby
rvm:
    - 2.3.3
    - 2.4

install: bundle install --without development

before_script:
  - "mysql -e 'create database unipept_test;'"
  - "cat backend/database/structure_no_index.sql | sed 's/unipept/unipept_test/' | mysql"
  - "sed -i '/socket/d;/password/d;s/username: unipept/username: travis/' config/database.yml"

sudo: false
